### ISSUE TITLE
Archlinux error: libj9jit29.so: cannot enable executable stack as shared object requires: Invalid argument

### ISSUE THREAD

**Issue by abcfy2** [ibmruntimes/Semeru-Runtimes#103]
```sh
jdk-21.0.6+7-jre/bin/java -version
JVMJ9VM011W Unable to load j9jit29: /jdk-21.0.6+7-jre/lib/default/libj9jit29.so: cannot enable executable stack as shared object requires: Invalid argument
openjdk version "21.0.6" 2025-01-21 LTS
IBM Semeru Runtime Open Edition 21.0.6.0 (build 21.0.6+7-LTS)
Eclipse OpenJ9 VM 21.0.6.0 (build openj9-0.49.0, JRE 21 Linux amd64-64-Bit Compressed References 20250121_380 (JIT disabled, AOT disabled)
OpenJ9   - 3c3d179854
OMR      - e49875871
JCL      - e01368f00df based on jdk-21.0.6+7)
```

You can reproduce this issue by use `archlinux` docker image:

```sh
docker run --rm -it archlinux
pacman -Sy --noconfirm wget
wget https://github.com/ibmruntimes/semeru21-binaries/releases/download/jdk-21.0.6%2B7_openj9-0.49.0/ibm-semeru-open-jre_x64_linux_21.0.6_7_openj9-0.49.0.tar.gz
tar xf ibm-semeru-open-jre_x64_linux_21.0.6_7_openj9-0.49.0.tar.gz
jdk-21.0.6+7-jre/bin/java -version
```

Then you can see:

```
JVMJ9VM011W Unable to load j9jit29: /jdk-21.0.6+7-jre/lib/default/libj9jit29.so: cannot enable executable stack as shared object requires: Invalid argument
openjdk version "21.0.6" 2025-01-21 LTS
IBM Semeru Runtime Open Edition 21.0.6.0 (build 21.0.6+7-LTS)
Eclipse OpenJ9 VM 21.0.6.0 (build openj9-0.49.0, JRE 21 Linux amd64-64-Bit Compressed References 20250121_380 (JIT disabled, AOT disabled)
OpenJ9   - 3c3d179854
OMR      - e49875871
JCL      - e01368f00df based on jdk-21.0.6+7)
```

**Comment by pshipton** [comment]
This should be fixed via https://github.com/eclipse-openj9/openj9/pull/21135

See also https://github.com/eclipse-openj9/openj9/issues/21156

**Comment by pshipton** [comment]
`Unable to load j9jit29` means no JIT.

Is it fixed with the M2 builds for the upcoming release?
https://github.com/ibmruntimes/semeru8-binaries/releases/tag/jdk8u452-b07_openj9-0.51.0-m2
https://github.com/ibmruntimes/semeru11-binaries/releases/tag/jdk-11.0.27%2B5_openj9-0.51.0-m2
https://github.com/ibmruntimes/semeru17-binaries/releases/tag/jdk-17.0.15%2B5_openj9-0.51.0-m2
https://github.com/ibmruntimes/semeru21-binaries/releases/tag/jdk-21.0.7%2B5_openj9-0.51.0-m2

**Comment by jhanders34** [comment]
@pshipton it appears to be fixed for the semeru builds for the ones that I have tried.  It is not fixed for IBM Java 8 though.  I just ran with IBM Java 8 SR8 FP 45 (the latest) and it still hits the problem.

**Comment by pshipton** [comment]
@jhanders34 do you have access to espresso head stream builds to try? Otherwise let me know which platforms and I'll make them available to you via Box. The problem was properly fixed after FP45 was released via https://github.com/eclipse-openj9/openj9/pull/21837 (and https://github.com/eclipse-omr/omr/pull/7747 for Semeru).
